---
engines:
  csslint:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  radon:
    enabled: true
  pep8:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - python
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/**/*
